# Generated by Django 5.0 on 2023-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
    ]
